'use strict'

angular.module('ymy.help.feed',[])
    .controller('helpAnFeed',['$scope','$state','$ionicViewSwitcher','userService',function($scope,$state,$ionicViewSwitcher,userService){
        $scope.feedRecord=function(){
            if(userService.userMess&&userService.userMess.accountId){
                $state.go('feedRecord',{});
                $ionicViewSwitcher.nextDirection('forward');
            }else{
                $state.go('login',{});
                $ionicViewSwitcher.nextDirection('forward');
            }
        }

        $scope.toQuestion=function(val){
            $state.go('questionList',{categoryId:val});
            $ionicViewSwitcher.nextDirection('forward');
        }
    }])
    .controller('feedBackRecord',['$scope','$state','$ionicViewSwitcher',function($scope,$state,$ionicViewSwitcher){
        $scope.toDetail=function(){
            $state.go('feedQuestion',{});
            $ionicViewSwitcher.nextDirection('forward');
        }
    }])
    .controller('questionList',['$scope','$state','$stateParams','$http','$ionicViewSwitcher','userService',function($scope,$state,$stateParams,$http,$ionicViewSwitcher,userService){
        if($stateParams.categoryId==71){
            $scope.viewTitle='云平台';
        }else if($stateParams.categoryId==72){
            $scope.viewTitle='艾德产品';
        }else{
            $scope.viewTitle='复苏小龙';
        }
        $scope.reqDate={
            categoryId:$stateParams.categoryId,
            sign:md5('ymy'+$stateParams.categoryId),
            pageNumber:1,
            pageSize:10
        }
        $scope.resData={
            totalPage:0,
            list:[]
        }
        requestDate();
        function requestDate(){
            $http({
                url:'ym/question2/list.api',
                method:'POST',
                params:$scope.reqDate
            }).success(function(data){
                console.log(data);
                if(data.result==1){
                    $scope.resData.totalPage=data.totalPage;
                    $scope.resData.list=data.categoryQuestionList;
                }else{
                    $scope.alertTab('参数错误');
                }
            })
        }
        $scope.toQuestionDetail=function(val){
            $state.go('commonQuestion',{question:val});
            $ionicViewSwitcher.nextDirection('forward');
        }
        $scope.feedQuestion=function(){
            if(userService.userMess&&userService.userMess.accountId){
                $state.go('toFeedQuestion',{cid:$stateParams.categoryId,group:$scope.viewTitle});
                $ionicViewSwitcher.nextDirection('forward');
            }else{
                $state.go('login',{});
                $ionicViewSwitcher.nextDirection('forward');
            }

        }
        $scope.loadMoreData=function(){

        }
    }])
    .controller('commonQuestion',['$scope','$state',function($scope,$state){
        $scope.question=$state.params.question;
        $scope.viewTitle=$scope.question.groupName;
    }])
    .controller('feedDetail',['$scope','$state',function($scope,$state){
        console.log('反馈问题详情');
    }])

    .controller('toFeedQues',['$scope','$stateParams','$http','userService',function($scope,$stateParams,$http,userService){
        $scope.stage=$stateParams.group;
        console.log($scope.stage);
        $scope.feedInfo={
            contact:'',
            question:''
        }
        $scope.feed=function(){
            if(!$scope.feedInfo.contact){
                $scope.alertTab('请填写常用联系方式');
                return;
            }

            if(!$scope.feedInfo.question){
                $scope.alertTab('请填写反馈问题');
                return;
            }
            console.log('------params----');
            console.log(
                userService.userMess.accountId,
                $stateParams.cid,
                $scope.feedInfo.contact,
                $scope.feedInfo.question

            );
            console.log('ymy'+$stateParams.cid+$scope.feedInfo.contact+userService.userMess.accountId+$scope.feedInfo.question);
            $http({
                url:'ym/question/add.api',
                method:'POST',
                params:{
                    publisher:userService.userMess.accountId,
                    categoryId:$stateParams.cid,
                    extstr1:encodeURI($scope.feedInfo.contact),
                    question:encodeURI($scope.feedInfo.question),
                    sign:md5('ymy'+$stateParams.cid+$scope.feedInfo.contact+userService.userMess.accountId+$scope.feedInfo.question)
                }
            }).success(function(data){
                console.log('------result----');
                console.log(data);
                if(data.result==1){
                    $scope.alertTab('反馈成功,请等待客服处理');
                    $scope._goback(-1);
                }else{
                    $scope.alertTab('反馈失败');
                }
            })

        }
    }])

